export interface ModelDef {
  id: string
  label: string
  desc: string
  tags?: string[]
  recommended?: boolean
}

export const PROVIDERS: { id: string; label: string; color: string; models: ModelDef[] }[] = [
  {
    id: 'claude', label: 'Claude', color: '#D97706',
    models: [
      { id: 'claude-sonnet-4-6', label: 'Sonnet 4.6', recommended: true,
        desc: 'Meilleur rapport qualité/prix selon Anthropic — développement, analyse et génération de contenu',
        tags: ['usage quotidien', 'développement', 'analyse'] },
      { id: 'claude-opus-4-7', label: 'Opus 4.7',
        desc: 'Modèle le plus puissant d\'Anthropic — raisonnement avancé, recherche approfondie, tâches complexes',
        tags: ['analyse complexe', 'recherche', 'raisonnement'] },
      { id: 'claude-haiku-4-5-20251001', label: 'Haiku 4.5',
        desc: 'Le plus rapide et économique d\'Anthropic — questions simples, classification, résumés',
        tags: ['rapide', 'économique', 'questions simples'] },
    ],
  },
  {
    id: 'openai', label: 'GPT', color: '#16A34A',
    models: [
      { id: 'gpt-5.5', label: 'GPT-5.5', recommended: true,
        desc: 'Modèle phare OpenAI — nouvelle classe d\'intelligence pour le raisonnement complexe et le code professionnel (contexte 1M)',
        tags: ['puissant', 'raisonnement', 'code'] },
      { id: 'gpt-5.4', label: 'GPT-5.4',
        desc: 'GPT-5.4 — très performant pour le code et le travail professionnel, excellent rapport qualité/prix ($2.50/MTok)',
        tags: ['polyvalent', 'code', 'agents'] },
      { id: 'gpt-5.4-mini', label: 'GPT-5.4 mini',
        desc: 'Version rapide et économique de GPT-5.4 — idéale pour les sous-agents et le computer use ($0.75/MTok)',
        tags: ['rapide', 'économique', 'code'] },
      { id: 'gpt-5.4-nano', label: 'GPT-5.4 nano',
        desc: 'Version ultra-légère de GPT-5.4 — la plus rapide et économique de la gamme, faible latence',
        tags: ['rapide', 'économique', 'volume'] },
      { id: 'gpt-4.1', label: 'GPT-4.1',
        desc: 'Génération précédente — bon suivi des instructions, polyvalent',
        tags: ['polyvalent'] },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini',
        desc: 'Version légère de GPT-4.1 — rapide et économique',
        tags: ['rapide', 'économique'] },
      { id: 'gpt-4o', label: 'GPT-4o',
        desc: 'Modèle multimodal de la génération précédente — toujours très performant',
        tags: ['multimodal', 'polyvalent'] },
      { id: 'o4-mini', label: 'o4 mini',
        desc: 'Modèle de raisonnement compact — très efficace sur le code et les maths, bon rapport qualité/prix',
        tags: ['raisonnement', 'code', 'économique'] },
      { id: 'o3', label: 'o3',
        desc: 'Meilleur modèle de raisonnement OpenAI — analyse approfondie et problèmes multi-étapes',
        tags: ['raisonnement', 'puissant', 'analyse'] },
      { id: 'o3-mini', label: 'o3 mini',
        desc: 'Raisonnement o3 en version économique — analytique et efficace',
        tags: ['raisonnement', 'économique'] },
    ],
  },
  {
    id: 'gemini', label: 'Gemini', color: '#2563EB',
    models: [
      { id: 'gemini-2.0-flash', label: '2.0 Flash', recommended: true,
        desc: 'Dernière génération Flash de Google — rapide, efficace et très bon pour l\'appel d\'outils',
        tags: ['rapide', 'usage quotidien', 'outils'] },
      { id: 'gemini-1.5-pro', label: '1.5 Pro',
        desc: 'Contexte jusqu\'à 2 millions de tokens — idéal pour analyser de longs documents ou une base de code entière',
        tags: ['contexte long', 'documents', 'développement'] },
      { id: 'gemini-1.5-flash', label: '1.5 Flash',
        desc: 'Flash équilibré de Google — rapide et efficace pour la grande majorité des requêtes',
        tags: ['rapide', 'économique'] },
    ],
  },
  {
    id: 'copilot', label: 'Copilot', color: '#6e40c9',
    models: [
      { id: 'gpt-4o',                     label: 'GPT-4o',           recommended: true,
        desc: 'GPT-4o polyvalent via Copilot Business — bon choix par défaut pour la plupart des tâches',
        tags: ['usage quotidien', 'polyvalent'] },
      { id: 'gpt-4o-mini',                label: 'GPT-4o mini',
        desc: 'Rapide et économique via Copilot — adapté aux questions simples et aux tâches répétitives',
        tags: ['rapide', 'économique'] },
      { id: 'gpt-5-mini',                 label: 'GPT-5 mini',
        desc: 'GPT-5 mini — nouvelle génération OpenAI, rapide et efficace',
        tags: ['rapide', 'nouvelle génération'] },
      { id: 'gpt-5.2',                    label: 'GPT-5.2',
        desc: 'GPT-5.2 via Copilot — capacités avancées de la gamme GPT-5',
        tags: ['polyvalent', 'GPT-5'] },
      { id: 'gpt-5.4',                    label: 'GPT-5.4',
        desc: 'GPT-5.4 — version la plus performante de la gamme GPT-5 via Copilot',
        tags: ['puissant', 'GPT-5'] },
      { id: 'gpt-5.2-codex',              label: 'GPT-5.2 Codex',
        desc: 'Codex GPT-5.2 — spécialisé par OpenAI pour la compréhension et la génération de code',
        tags: ['développement', 'technique'] },
      { id: 'gpt-5.3-codex',              label: 'GPT-5.3 Codex',
        desc: 'Codex GPT-5.3 — version améliorée du Codex, pour les tâches de développement avancées',
        tags: ['développement', 'technique'] },
      { id: 'o1-mini',                    label: 'o1 mini',
        desc: 'Modèle de raisonnement d\'OpenAI — résolution de problèmes complexes par étapes',
        tags: ['raisonnement', 'maths', 'développement'] },
      { id: 'o3-mini',                    label: 'o3 mini',
        desc: 'o3 mini — dernier modèle de raisonnement OpenAI, très performant sur les tâches analytiques',
        tags: ['raisonnement', 'analyse'] },
      { id: 'claude-3-5-sonnet-20241022', label: 'Claude 3.5 Sonnet',
        desc: 'Claude 3.5 Sonnet (oct. 2024) via Copilot — développement et analyse générale',
        tags: ['développement', 'analyse'] },
      { id: 'claude-3-7-sonnet-20250219', label: 'Claude 3.7 Sonnet',
        desc: 'Claude 3.7 Sonnet — alliance entre raisonnement approfondi et réponse rapide (Anthropic)',
        tags: ['développement', 'raisonnement'] },
      { id: 'claude-sonnet-4-5',          label: 'Claude Sonnet 4.5',
        desc: 'Claude Sonnet 4.5 — quatrième génération Anthropic, développement et analyse',
        tags: ['développement', 'analyse'] },
      { id: 'claude-sonnet-4-6',          label: 'Claude Sonnet 4.6',
        desc: 'Claude Sonnet 4.6 — meilleur Sonnet d\'Anthropic disponible via Copilot Business',
        tags: ['usage quotidien', 'développement'] },
      { id: 'claude-opus-4-5',            label: 'Claude Opus 4.5',
        desc: 'Claude Opus 4.5 — très puissant pour les tâches longues et complexes via Copilot',
        tags: ['analyse complexe', 'raisonnement'] },
      { id: 'claude-opus-4-6',            label: 'Claude Opus 4.6',
        desc: 'Claude Opus 4.6 — encore plus puissant, recherche et synthèse avancées',
        tags: ['analyse complexe', 'recherche'] },
      { id: 'claude-opus-4-7',            label: 'Claude Opus 4.7',
        desc: 'Claude Opus 4.7 — le plus puissant d\'Anthropic disponible via Copilot',
        tags: ['analyse complexe', 'recherche'] },
      { id: 'claude-haiku-4-5',           label: 'Claude Haiku 4.5',
        desc: 'Claude Haiku 4.5 — ultra-rapide et très économique via Copilot',
        tags: ['rapide', 'économique'] },
      { id: 'gemini-2.5-pro',             label: 'Gemini 2.5 Pro',
        desc: 'Gemini 2.5 Pro via Copilot — grand contexte de Google, idéal pour les tâches complexes',
        tags: ['contexte long', 'analyse'] },
      { id: 'gemini-3.1-pro',             label: 'Gemini 3.1 Pro',
        desc: 'Gemini 3.1 Pro — dernière génération Google, très performant',
        tags: ['polyvalent', 'nouvelle génération'] },
      { id: 'gemini-3-flash',             label: 'Gemini 3 Flash',
        desc: 'Gemini 3 Flash — troisième génération Google, rapide via Copilot',
        tags: ['rapide'] },
      { id: 'grok-code-fast-1',           label: 'Grok Code Fast',
        desc: 'xAI Grok Code — conçu par xAI pour la compréhension et la génération de code',
        tags: ['développement', 'rapide'] },
    ],
  },
  {
    id: 'github', label: 'GitHub', color: '#24292f',
    models: [
      // ── OpenAI via GitHub Models ──
      { id: 'gpt-5',                         label: 'GPT-5', recommended: true,
        desc: 'GPT-5 via GitHub Models — modèle phare OpenAI, inclus dans GitHub Free/Pro',
        tags: ['puissant', 'polyvalent'] },
      { id: 'gpt-5-mini',                    label: 'GPT-5 mini',
        desc: 'GPT-5 mini — version rapide et économique de GPT-5 via GitHub',
        tags: ['rapide', 'économique'] },
      { id: 'gpt-5-nano',                    label: 'GPT-5 nano',
        desc: 'GPT-5 nano — ultra-léger, faible latence via GitHub Models',
        tags: ['rapide', 'économique'] },
      { id: 'gpt-4o',                        label: 'GPT-4o',
        desc: 'GPT-4o — modèle multimodal OpenAI de génération précédente via GitHub',
        tags: ['polyvalent'] },
      { id: 'gpt-4o-mini',                   label: 'GPT-4o mini',
        desc: 'GPT-4o mini — rapide et économique via GitHub Models',
        tags: ['rapide', 'économique'] },
      { id: 'o3',                            label: 'o3',
        desc: 'o3 — modèle de raisonnement OpenAI via GitHub (Copilot Pro requis)',
        tags: ['raisonnement', 'puissant'] },
      { id: 'o3-mini',                       label: 'o3 mini',
        desc: 'o3 mini — raisonnement OpenAI économique via GitHub',
        tags: ['raisonnement', 'économique'] },
      { id: 'o4-mini',                       label: 'o4 mini',
        desc: 'o4 mini — raisonnement compact nouvelle génération via GitHub (Copilot Pro requis)',
        tags: ['raisonnement', 'code'] },
      // ── Anthropic ──
      { id: 'claude-3-7-sonnet-20250219',    label: 'Claude 3.7 Sonnet',
        desc: 'Claude 3.7 Sonnet via GitHub Models — raisonnement approfondi',
        tags: ['développement', 'raisonnement'] },
      { id: 'claude-3-5-sonnet-20241022',    label: 'Claude 3.5 Sonnet',
        desc: 'Claude 3.5 Sonnet via GitHub Models — développement et analyse',
        tags: ['développement'] },
      // ── Meta Llama ──
      { id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', label: 'Llama 4 Scout',
        desc: 'Llama 4 Scout — dernière génération Meta, multimodal, contexte 10M tokens',
        tags: ['open source', 'multimodal', 'contexte long'] },
      { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct', label: 'Llama 4 Maverick',
        desc: 'Llama 4 Maverick — très performant, contexte 1M, meilleur Llama open source',
        tags: ['open source', 'puissant'] },
      { id: 'Llama-3.1-405B-Instruct',       label: 'Llama 3.1 405B',
        desc: 'Llama 3.1 405B — grand modèle open source Meta, très performant',
        tags: ['open source'] },
      // ── xAI Grok ──
      { id: 'grok-3',                        label: 'Grok-3',
        desc: 'Grok-3 de xAI — très performant pour le raisonnement et l\'analyse via GitHub',
        tags: ['raisonnement', 'analyse'] },
      { id: 'grok-3-mini',                   label: 'Grok-3 mini',
        desc: 'Grok-3 mini — version économique de Grok-3 via GitHub Models',
        tags: ['rapide', 'économique'] },
      // ── DeepSeek ──
      { id: 'DeepSeek-R1',                   label: 'DeepSeek R1',
        desc: 'DeepSeek R1 — modèle de raisonnement open source très performant, alternatif à o3',
        tags: ['raisonnement', 'open source'] },
      { id: 'DeepSeek-R1-0528',              label: 'DeepSeek R1 (05/28)',
        desc: 'DeepSeek R1 (version mai 2028) — améliorations raisonnement et instruction following',
        tags: ['raisonnement', 'open source'] },
      // ── Mistral ──
      { id: 'mistral-large-2407',             label: 'Mistral Large',
        desc: 'Mistral Large — modèle européen, efficace et polyvalent via GitHub Models',
        tags: ['polyvalent'] },
      // ── Microsoft Phi ──
      { id: 'Phi-4',                          label: 'Phi-4',
        desc: 'Phi-4 de Microsoft — petite taille mais très performant pour le raisonnement et le code',
        tags: ['compact', 'code', 'raisonnement'] },
      { id: 'Phi-3.5-mini-instruct',          label: 'Phi-3.5 mini',
        desc: 'Phi-3.5 mini — ultra-compact de Microsoft, rapide pour les tâches simples',
        tags: ['rapide', 'économique'] },
    ],
  },
]
