export interface ModelDef {
  id: string
  label: string
  desc: string
  tags?: string[]
  recommended?: boolean
}

export const PROVIDERS: { id: string; label: string; color: string; models: ModelDef[] }[] = [
  {
    id: 'claude', label: 'Claude', color: '#D97706',
    models: [
      { id: 'claude-sonnet-4-6', label: 'Sonnet 4.6', recommended: true,
        desc: 'Meilleur rapport qualité/prix selon Anthropic — développement, analyse et génération de contenu',
        tags: ['usage quotidien', 'développement', 'analyse'] },
      { id: 'claude-opus-4-7', label: 'Opus 4.7',
        desc: 'Modèle le plus puissant d\'Anthropic — raisonnement avancé, recherche approfondie, tâches complexes',
        tags: ['analyse complexe', 'recherche', 'raisonnement'] },
      { id: 'claude-haiku-4-5-20251001', label: 'Haiku 4.5',
        desc: 'Le plus rapide et économique d\'Anthropic — questions simples, classification, résumés',
        tags: ['rapide', 'économique', 'questions simples'] },
    ],
  },
  {
    id: 'openai', label: 'GPT', color: '#16A34A',
    models: [
      { id: 'gpt-4o', label: 'GPT-4o', recommended: true,
        desc: 'Modèle phare d\'OpenAI — multimodal et polyvalent, recommandé pour la plupart des tâches',
        tags: ['usage quotidien', 'polyvalent', 'multimodal'] },
      { id: 'gpt-4o-mini', label: 'GPT-4o mini',
        desc: 'Version légère et rapide d\'OpenAI — recommandée pour les tâches simples et les volumes importants',
        tags: ['rapide', 'économique', 'volume'] },
      { id: 'o1-mini', label: 'o1 mini',
        desc: 'Modèle de raisonnement d\'OpenAI — analyse étape par étape, idéal pour les maths et les problèmes complexes',
        tags: ['raisonnement', 'maths', 'développement'] },
    ],
  },
  {
    id: 'gemini', label: 'Gemini', color: '#2563EB',
    models: [
      { id: 'gemini-2.0-flash', label: '2.0 Flash', recommended: true,
        desc: 'Dernière génération Flash de Google — rapide, efficace et très bon pour l\'appel d\'outils',
        tags: ['rapide', 'usage quotidien', 'outils'] },
      { id: 'gemini-1.5-pro', label: '1.5 Pro',
        desc: 'Contexte jusqu\'à 2 millions de tokens — idéal pour analyser de longs documents ou une base de code entière',
        tags: ['contexte long', 'documents', 'développement'] },
      { id: 'gemini-1.5-flash', label: '1.5 Flash',
        desc: 'Flash équilibré de Google — rapide et efficace pour la grande majorité des requêtes',
        tags: ['rapide', 'économique'] },
    ],
  },
  {
    id: 'copilot', label: 'Copilot', color: '#6e40c9',
    models: [
      { id: 'gpt-4o',                     label: 'GPT-4o',           recommended: true,
        desc: 'GPT-4o polyvalent via Copilot Business — bon choix par défaut pour la plupart des tâches',
        tags: ['usage quotidien', 'polyvalent'] },
      { id: 'gpt-4o-mini',                label: 'GPT-4o mini',
        desc: 'Rapide et économique via Copilot — adapté aux questions simples et aux tâches répétitives',
        tags: ['rapide', 'économique'] },
      { id: 'gpt-5-mini',                 label: 'GPT-5 mini',
        desc: 'GPT-5 mini — nouvelle génération OpenAI, rapide et efficace',
        tags: ['rapide', 'nouvelle génération'] },
      { id: 'gpt-5.2',                    label: 'GPT-5.2',
        desc: 'GPT-5.2 via Copilot — capacités avancées de la gamme GPT-5',
        tags: ['polyvalent', 'GPT-5'] },
      { id: 'gpt-5.4',                    label: 'GPT-5.4',
        desc: 'GPT-5.4 — version la plus performante de la gamme GPT-5 via Copilot',
        tags: ['puissant', 'GPT-5'] },
      { id: 'gpt-5.2-codex',              label: 'GPT-5.2 Codex',
        desc: 'Codex GPT-5.2 — spécialisé par OpenAI pour la compréhension et la génération de code',
        tags: ['développement', 'technique'] },
      { id: 'gpt-5.3-codex',              label: 'GPT-5.3 Codex',
        desc: 'Codex GPT-5.3 — version améliorée du Codex, pour les tâches de développement avancées',
        tags: ['développement', 'technique'] },
      { id: 'o1-mini',                    label: 'o1 mini',
        desc: 'Modèle de raisonnement d\'OpenAI — résolution de problèmes complexes par étapes',
        tags: ['raisonnement', 'maths', 'développement'] },
      { id: 'o3-mini',                    label: 'o3 mini',
        desc: 'o3 mini — dernier modèle de raisonnement OpenAI, très performant sur les tâches analytiques',
        tags: ['raisonnement', 'analyse'] },
      { id: 'claude-3-5-sonnet-20241022', label: 'Claude 3.5 Sonnet',
        desc: 'Claude 3.5 Sonnet (oct. 2024) via Copilot — développement et analyse générale',
        tags: ['développement', 'analyse'] },
      { id: 'claude-3-7-sonnet-20250219', label: 'Claude 3.7 Sonnet',
        desc: 'Claude 3.7 Sonnet — alliance entre raisonnement approfondi et réponse rapide (Anthropic)',
        tags: ['développement', 'raisonnement'] },
      { id: 'claude-sonnet-4-5',          label: 'Claude Sonnet 4.5',
        desc: 'Claude Sonnet 4.5 — quatrième génération Anthropic, développement et analyse',
        tags: ['développement', 'analyse'] },
      { id: 'claude-sonnet-4-6',          label: 'Claude Sonnet 4.6',
        desc: 'Claude Sonnet 4.6 — meilleur Sonnet d\'Anthropic disponible via Copilot Business',
        tags: ['usage quotidien', 'développement'] },
      { id: 'claude-opus-4-5',            label: 'Claude Opus 4.5',
        desc: 'Claude Opus 4.5 — très puissant pour les tâches longues et complexes via Copilot',
        tags: ['analyse complexe', 'raisonnement'] },
      { id: 'claude-opus-4-6',            label: 'Claude Opus 4.6',
        desc: 'Claude Opus 4.6 — encore plus puissant, recherche et synthèse avancées',
        tags: ['analyse complexe', 'recherche'] },
      { id: 'claude-opus-4-7',            label: 'Claude Opus 4.7',
        desc: 'Claude Opus 4.7 — le plus puissant d\'Anthropic disponible via Copilot',
        tags: ['analyse complexe', 'recherche'] },
      { id: 'claude-haiku-4-5',           label: 'Claude Haiku 4.5',
        desc: 'Claude Haiku 4.5 — ultra-rapide et très économique via Copilot',
        tags: ['rapide', 'économique'] },
      { id: 'gemini-2.5-pro',             label: 'Gemini 2.5 Pro',
        desc: 'Gemini 2.5 Pro via Copilot — grand contexte de Google, idéal pour les tâches complexes',
        tags: ['contexte long', 'analyse'] },
      { id: 'gemini-3.1-pro',             label: 'Gemini 3.1 Pro',
        desc: 'Gemini 3.1 Pro — dernière génération Google, très performant',
        tags: ['polyvalent', 'nouvelle génération'] },
      { id: 'gemini-3-flash',             label: 'Gemini 3 Flash',
        desc: 'Gemini 3 Flash — troisième génération Google, rapide via Copilot',
        tags: ['rapide'] },
      { id: 'grok-code-fast-1',           label: 'Grok Code Fast',
        desc: 'xAI Grok Code — conçu par xAI pour la compréhension et la génération de code',
        tags: ['développement', 'rapide'] },
    ],
  },
  {
    id: 'github', label: 'GitHub', color: '#24292f',
    models: [
      { id: 'gpt-4o',                        label: 'GPT-4o',           recommended: true,
        desc: 'GPT-4o via GitHub Models — inclus dans les abonnements GitHub Free et Pro' },
      { id: 'gpt-4o-mini',                   label: 'GPT-4o mini',
        desc: 'Ultra-rapide et économique via GitHub Models' },
      { id: 'claude-3-5-sonnet-20241022',    label: 'Claude 3.5',
        desc: 'Claude 3.5 Sonnet via GitHub Models — bon équilibre entre qualité et vitesse' },
      { id: 'claude-3-7-sonnet-20250219',    label: 'Claude 3.7',
        desc: 'Claude 3.7 Sonnet via GitHub Models — raisonnement approfondi' },
      { id: 'Llama-3.2-90B-Vision-Instruct', label: 'Llama 3.2 90B',
        desc: 'Open source Meta — alternative gratuite et performante via GitHub Models' },
      { id: 'Llama-3.1-405B-Instruct',       label: 'Llama 3.1 405B',
        desc: 'Le plus grand modèle Llama open source — très performant' },
      { id: 'mistral-large-2407',             label: 'Mistral Large',
        desc: 'Mistral Large via GitHub Models — modèle européen, efficace et polyvalent' },
      { id: 'Phi-3.5-mini-instruct',          label: 'Phi-3.5 mini',
        desc: 'Modèle compact de Microsoft — ultra-rapide pour les tâches simples' },
    ],
  },
]
