// Odoo design tokens — sourced from odoo/odoo primary_variables.scss
export const t = {
  brand:        '#714B67',
  brandLight:   '#875A7B',
  brandDark:    '#5c3d54',
  action:       '#017e84',
  actionHover:  '#016670',
  bg:           '#f0eeeb',
  white:        '#ffffff',
  text:         '#212529',
  muted:        '#6c757d',
  border:       '#dee2e6',
  borderLight:  '#e9ecef',
  success:      '#28a745',
  warning:      '#ffac00',
  danger:       '#dc3545',
  info:         '#17a2b8',
  shadow:       '0 1px 3px rgba(0,0,0,.12)',
  shadowMd:     '0 2px 8px rgba(0,0,0,.15)',
  radius:       '4px',
  radiusSm:     '3px',
  radiusLg:     '6px',
  font:         "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  fontSize:     '14px',
  navWidth:     '220px',
} as const
